# Generated by Django 5.1.7 on 2025-08-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='image_template_url',
        ),
    ]
