# Generated by Django 5.1.7 on 2025-08-05 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_remove_ticket_template_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_image_id',
            field=models.CharField(blank=True, help_text='Extracted Google Drive file ID', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='banner_image_url',
            field=models.URLField(blank=True, help_text='Google Drive shareable link for banner image'),
        ),
        migrations.CreateModel(
            name='EventSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=200)),
                ('logo_url', models.URLField(help_text='Google Drive shareable link for sponsor logo')),
                ('logo_id', models.CharField(blank=True, help_text='Extracted Google Drive file ID', max_length=200)),
                ('website_url', models.URLField(blank=True, help_text="Sponsor's website URL")),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='ticketing.event')),
            ],
            options={
                'ordering': ['order', 'sponsor_name'],
            },
        ),
    ]
