# Generated by Django 5.1.7 on 2025-08-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_event_banner_image_id_event_banner_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsponsor',
            name='sponsor_type',
            field=models.CharField(blank=True, help_text='Type of sponsorship (e.g., Ticketing Partner, Gold Sponsor, Venue Partner)', max_length=100),
        ),
    ]
