# Generated by Django 5.1.7 on 2025-08-06 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_payment_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='purchase_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticketing.paymenttransaction'),
        ),
    ]
