# Generated by Django 5.1.7 on 2025-08-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_eventcommission_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_start_date',
            field=models.DateTimeField(blank=True, help_text='When ticket sales begin', null=True),
        ),
    ]
