# Generated by Django 5.1.7 on 2025-08-08 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0009_event_registration_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='cf_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketing.event'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
