# Generated by Django 5.1.7 on 2025-08-08 06:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_paymenttransaction_cf_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='unique_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
