# Generated by Django 5.1.7 on 2025-08-08 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0011_ticket_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='unique_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
