# Generated by Django 5.1.7 on 2025-08-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0012_alter_ticket_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booking_quantity',
            field=models.IntegerField(default=1, help_text='Number of tickets booked to create this consolidated ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_admission_count',
            field=models.IntegerField(default=1, help_text='Total number of people this ticket admits'),
        ),
    ]
