# Generated by Django 5.2.5 on 2025-08-09 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0013_ticket_booking_quantity_ticket_total_admission_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='ticketing.ticket'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('ticket', 'transaction')},
        ),
    ]
