# Generated by Django 5.2.5 on 2025-08-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0014_fix_duplicate_invoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image_url',
            field=models.TextField(blank=True, help_text='Google Drive shareable link or iframe code for banner image'),
        ),
        migrations.AlterField(
            model_name='eventsponsor',
            name='logo_url',
            field=models.TextField(help_text='Google Drive shareable link or iframe code for sponsor logo'),
        ),
    ]
